### ISSUE TITLE
Static ShadowUI functions don't available via hammerhead api

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [superroma/testcafe-hammerhead#148]
TestCafe uses `addClass` and `removeClass`, they are not available now via api.
This issue stops https://github.com/superroma/testcafe-phoenix/issues/44

**Comment by inikulin** [comment]
@AlexanderMoskovkin and everyone: Let's not use documentation requirement and modification level labels **while issue is open**. We will not pollute issue with yet unused labels and it's not always clear until the issue is not fixed if it requires documentation or major version bump. It's better to perform this analysis afterwards.
